import { Column, CreateDateColumn, Entity, PrimaryGeneratedColumn } from 'typeorm';
import { NutrientCategory } from '../fertiliser-plan/fertiliser-product.entity';

/**
 * A simulated/local group-buy deal for one product — spec sections 10-13's
 * "FarmReturn Buying Offer". Offers are created directly for this prototype
 * (POST /group-buy-offers, any authenticated user) rather than generated by
 * a supplier RFQ pipeline; in production this would be restricted to an
 * ops/admin role, or auto-generated from aggregated fertiliser-plan demand
 * across farms in a county — both are real future work, not simulated here.
 *
 * `fertiliserProductCategory` is the honest-scoping hook: when it's set (lime,
 * phosphorus or potassium), a farm's requirement for this offer is read
 * straight from FertiliserPlanService — never guessed. When it's null (e.g.
 * a nitrogen product like protected urea, which this API has no requirement
 * model for yet — see FertiliserPlanService), the farmer must state their own
 * requirement when joining.
 */
@Entity('group_buy_offers')
export class GroupBuyOffer {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'product_name' })
  productName: string;

  @Column({
    type: 'enum',
    enum: NutrientCategory,
    name: 'fertiliser_product_category',
    nullable: true,
  })
  fertiliserProductCategory: NutrientCategory | null;

  /** Null = nationwide; otherwise matches Farm.county for eligibility grouping. */
  @Column({ type: 'varchar', nullable: true })
  county: string | null;

  @Column({ type: 'numeric', precision: 8, scale: 2, name: 'typical_price_per_tonne_eur' })
  typicalPricePerTonneEur: number;

  @Column({ type: 'numeric', precision: 8, scale: 2, name: 'negotiated_price_per_tonne_eur' })
  negotiatedPricePerTonneEur: number;

  @Column({ type: 'numeric', precision: 8, scale: 1, name: 'supplier_threshold_tonnes' })
  supplierThresholdTonnes: number;

  @Column({ type: 'timestamptz', name: 'expires_at' })
  expiresAt: Date;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;
}
